export const EMOJI_MAP = [
['😀',['smile','happy','glücklich','gluecklich','lächeln','laecheln','freude']],['😂',['laugh','lachen','lustig','haha']],['😍',['love','liebe','verliebt']],['🥳',['party','feier','geburtstag','birthday']],['😴',['sleep','schlafen','müde','muede']],['🤒',['krank','sick','fieber','fever']],['😎',['cool','sonne','sun']],['😭',['cry','weinen','traurig','sad']],['😡',['angry','wütend','wuetend']],['🤔',['denken','think','überlegen','ueberlegen']],
['👶',['baby','babys','säugling','saeugling','infant']],['🧒',['ki','kind','kinder','kid','kids','child','children','tochter','sohn','daughter','son']],['👧',['mädchen','maedchen','girl']],['👦',['junge','boy']],['👨‍👩‍👧‍👦',['familie','family','eltern','parents']],['🍼',['flasche','milchflasche','bottle','baby bottle']],['🧷',['windel','diaper','nappy']],['🧸',['spielzeug','toy','teddy']],['🎒',['kita','kindergarten','schule','school','rucksack']],
['🥑',['avocado','avocados','avo']],['🍎',['apfel','apple']],['🍌',['banane','banana']],['🍓',['erdbeere','strawberry']],['🫐',['beeren','berries','blueberry','blaubeere']],['🍋',['zitrone','lemon']],['🍊',['orange','mandarine']],['🍇',['trauben','grapes']],['🍉',['wassermelone','melon','melone','watermelon']],['🍈',['melone','melon','honigmelone']],['🍍',['ananas','pineapple']],['🥭',['mango']],['🥝',['kiwi']],['🍅',['tomate','tomato']],['🥦',['brokkoli','broccoli','gemüse','vegetables','veggies']],['🥕',['karotte','möhre','moehre','carrot']],['🧅',['zwiebel','onion']],['🥔',['kartoffel','potato']],['🥬',['salat','lettuce','greens']],['🌶️',['chili','scharf','pepper']],['🥚',['ei','eggs','egg']],['🧀',['käse','kaese','cheese']],['🍞',['brot','bread','bakery','bäckerei','baeckerei']],['🥐',['croissant']],['🥨',['brezel','pretzel']],['🥯',['bagel']],['🥞',['pfannkuchen','pancake']],['🧇',['waffel','waffle']],['🥓',['speck','bacon']],['🍗',['hähnchen','haehnchen','chicken']],['🥩',['fleisch','meat','steak']],['🍔',['burger','hamburger']],['🍟',['pommes','fries']],['🍕',['pizza']],['🌭',['hotdog']],['🥪',['sandwich','brotzeit']],['🌮',['taco']],['🌯',['wrap','burrito']],['🥗',['salat','salad']],['🍝',['pasta','nudeln','spaghetti']],['🍜',['ramen','suppe','soup']],['🍚',['reis','rice']],['🍣',['sushi']],['🍰',['kuchen','cake']],['🎂',['geburtstag','birthday','torte']],['🍫',['schokolade','chocolate']],['🍪',['keks','cookie']],['🍯',['honig','honey']],['🥛',['milch','milk']],['☕',['kaffee','coffee','espresso','cappuccino']],['🍵',['tee','tea']],['🧃',['saft','juice']],['🥤',['getränk','getraenk','drink','softdrink']],['🍷',['wein','wine']],['🍺',['bier','beer']],
['🧴',['eincremen','cremen','creme','lotion','salbe','sonnencreme','sunscreen','cream','moisturizer','skincare']],['🧼',['seife','soap','waschen','wash']],['🚿',['dusche','duschen','shower']],['🛁',['baden','bad','bath']],['🪒',['rasieren','shave']],['💇',['haare','friseur','haircut','hair']],['💅',['nägel','naegel','nails','manicure']],['🪥',['zahnbürste','zahnbuerste','toothbrush']],['🦷',['zähne','zaehne','zahn','teeth','tooth','zahnarzt','zähneputzen']],['👓',['brille','glasses']],['🦻',['hörgerät','hoergeraet','hearing']],['🧻',['toilette','wc','toilet','klopapier']],
['🩺',['arzt','ärztin','doctor','medical','checkup','untersuchung','kontrolle','praxis','arzttermin']],['🏥',['krankenhaus','hospital']],['💊',['medizin','medicine','medication','pill','tablette','medikament','vitamin','pille']],['💉',['impfung','vaccine','shot','spritze']],['🧪',['labor','test','lab']],['🩹',['pflaster','bandage']],['🩼',['krücke','kruecke','crutch']],['🧠',['therapie','therapy','mental','mind','denken']],['🫁',['atmen','breathing','breath','lunge']],['❤️',['herz','heart','love','liebe']],
['📅',['termin','appointment','meeting','kalender','date','schedule']],['⏰',['wecker','alarm','reminder','erinnerung']],['🕒',['zeit','time','uhr']],['📌',['pin','merken','remember']],['✅',['todo','aufgabe','task','check','erledigen']],['📝',['schreiben','write','journal','tagebuch','notes','notizen']],['📚',['lesen','read','reading','book','buch','lernen','study']],['📖',['roman','novel','bibel','bible']],['📄',['dokument','document','paper']],['🧾',['quittung','receipt','beleg','rechnung','expense','ausgabe']],['📦',['paket','package','parcel']],['✉️',['mail','email','e-mail','post','brief']],['📞',['call','phone','anruf','telefonieren','telefon']],['🔍',['suchen','search','find']],['⭐',['stern','star','favorite','favorit']],
['💸',['zahlen','rechnung','bezahlen','bill','pay','payment','invoice','steuer','tax']],['💰',['sparen','saving','save money','geld','money']],['🪙',['münze','muenze','coin']],['🏦',['bank','konto','account']],['💳',['karte','card','credit card','kreditkarte']],['📈',['statistik','aktien','stocks','chart']],['📉',['verlust','loss','down']],
['🏃',['laufen','run','running','jog','joggen']],['🚶',['spaziergang','spazier','walk','walking','gehen']],['💪',['gym','workout','training','sport','kraft','krafttraining','mini krafttraining','fitness','exercise','übung','uebung']],['🧘',['meditation','meditate','achtsam','meditieren','yoga','mindful']],['🤸',['turnen','gymnastik','mobility']],['🏊',['schwimmen','swim','swimming']],['🚴',['fahrrad','bike','bicycle','cycling']],['⚽',['fußball','fussball','football','soccer']],['🏀',['basketball']],['🎾',['tennis']],['🏐',['volleyball']],['🏓',['pingpong','tischtennis']],['⛳',['golf']],['🥊',['boxen','boxing']],['⛷️',['ski','skifahren']],['🏂',['snowboard']],
['🧹',['putzen','clean','cleaning','aufräumen','tidy','ordnung']],['🧺',['wäsche','waesche','laundry','waschen','wash clothes']],['🛒',['einkauf','einkaufen','shopping','groceries','supermarkt']],['🌱',['pflanze','pflanzen','gießen','giessen','plant','garden','garten']],['🪴',['umtopfen','repot','topfpflanze']],['🧽',['schwamm','sponge']],['🪟',['fenster','window']],['🗑️',['müll','muell','trash','abfall','garbage','recycling']],['🛠️',['werkzeug','tools','wartung','maintenance']],['🔧',['reparieren','repair','fix','tool']],['🔑',['schlüssel','schluessel','key']],['🏠',['haus','home','wohnung','zuhause']],['🛏️',['bett','bed','sleep','schlafen']],['🪑',['stuhl','chair']],['🛋️',['sofa','couch']],['🚪',['tür','tuer','door']],['🪞',['spiegel','mirror']],
['🚗',['auto','car','fahren','drive','tanken','benzin']],['⛽',['tankstelle','fuel','gas station']],['🚆',['zug','train','bahn']],['🚌',['bus']],['✈️',['flug','flight','plane','airport','flughafen']],['🚕',['taxi']],['🚲',['bike','fahrrad','bicycle']],['🛴',['scooter','roller']],['🚢',['schiff','ship','boat']],['🧳',['reise','travel','packen','packing','koffer']],['🪪',['ausweis','id','passport','pass']],['🗺️',['karte','map','route']],
['💻',['code','coding','programmieren','computer','laptop','entwickeln']],['📱',['handy','phone','smartphone']],['🔋',['akku','battery','laden','charge']],['🔌',['stecker','plug']],['📷',['foto','photo','camera']],['🎧',['musik','music','podcast','listen','hören']],['🎬',['film','movie','kino']],['📺',['tv','fernsehen']],['🎮',['game','gaming','spiel']],['📰',['news','nachrichten']],['💡',['idee','idea','licht','light']],['🖨️',['drucker','printer','print']],['💾',['speichern','save file','disk']],
['🎨',['malen','paint','painting','zeichnen','draw','kunst']],['🎹',['klavier','piano']],['🎸',['gitarre','guitar']],['🎤',['singen','sing','microphone']],['🎵',['lied','song','music']],['📸',['fotografie','photography']],['🧩',['puzzle','rätsel','raetsel']],['🎲',['würfel','wuerfel','dice','boardgame']],['🪡',['nähen','naehen','sew']],['🧶',['stricken','knit','wolle']],
['🐕',['hund','dog','gassi']],['🐈',['katze','kater','cat']],['🐟',['fisch','fish']],['🐦',['vogel','bird']],['🐰',['hase','rabbit']],['🐹',['hamster']],['🐴',['pferd','horse']],['🐝',['biene','bee']],['🦋',['schmetterling','butterfly']],['🌳',['baum','tree']],['🌷',['blume','flower']],['🌿',['kraut','herb','herbs']],
['☀️',['morgen','morning','sun','sonne','sunlight']],['🌙',['abend','evening','night','nacht']],['🌧️',['regen','rain']],['❄️',['schnee','snow']],['☂️',['schirm','umbrella','regen']],['🔥',['feuer','fire','heizen']],['🕯️',['kerze','candle']],['🌈',['regenbogen','rainbow']],['⚡',['strom','power','lightning']],
['🙏',['beten','pray','prayer']],['🎁',['geschenk','gift','present']],['🏆',['preis','award','trophy','gewinn']],['🎯',['ziel','goal','target']],['🚩',['flagge','flag','markieren']],['🔒',['lock','schloss','sperren']],['🔓',['unlock','entsperren']],['📍',['ort','place','location']],['💬',['chat','message','nachricht']],['🧑‍💼',['arbeit','work','job','office','büro','buero']],['🧑‍🏫',['lehrer','teacher','schule','school']],['🧑‍🍳',['kochen','cook','cooking','meal prep']],['👕',['kleidung','clothes','shirt']],['👟',['schuhe','shoes']],['🧦',['socken','socks']],['🧣',['schal','scarf']],['🧤',['handschuhe','gloves']],['☕',['pause','break','kaffeepause']]
];
